// Package main — sirsi-menubar
//
// ☥ Sirsi Menu Bar Application (ADR-010)
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"fyne.io/systray"
	"github.com/SirsiMaster/sirsi-pantheon/internal/platform"
)

var version = "v0.10.0"

func main() {
	unlock, err := platform.TryLock("menubar")
	if err != nil {
		fmt.Printf("☥ Sirsi Menubar is already running. Exiting.\n")
		os.Exit(0)
	}
	defer unlock()

	if os.Getenv("SIRSI_HEADLESS") == "1" {
		runHeadless()
		return
	}

	systray.Run(onReady, onExit)
}

func runHeadless() {
	fmt.Printf("☥ Sirsi Menubar %s (Headless Mode)\n", version)
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
	<-sigCh
}

func onReady() {
	systray.SetTemplateIcon(AnkhIcon, AnkhIcon)
	systray.SetTitle("Sirsi")
	systray.SetTooltip("Sirsi Ecosystem Monitor")

	// ── Stats section ───────────────────────────────────────────────
	mStats := systray.AddMenuItem("Loading...", "Click to refresh stats")
	systray.AddSeparator()

	// ── Ra section ──────────────────────────────────────────────────
	mRaHeader := systray.AddMenuItem("𓇶 Ra — Orchestrator", "Click to open Command Center")
	mRaDeploy := systray.AddMenuItem("  Deploy All Scopes", "sirsi ra deploy")
	mRaKill := systray.AddMenuItem("  Kill All Windows", "sirsi ra kill")
	mRaCollect := systray.AddMenuItem("  Collect Results", "sirsi ra collect")

	// Ra scope status items (updated dynamically, clickable to view logs)
	raScopes := make([]*systray.MenuItem, 4)
	for i := range raScopes {
		raScopes[i] = systray.AddMenuItem("  —", "Click to view scope log")
	}

	systray.AddSeparator()

	// ── Sirsi commands ─────────────────────────────────────────────
	mScan := systray.AddMenuItem("𓁢 Scan (Weigh)", "Scan for waste")
	mJudge := systray.AddMenuItem("⚖️ Judge", "Apply policies")
	mKa := systray.AddMenuItem("𓂓 Ka (Ghost Hunt)", "Detect dead apps")
	mMaat := systray.AddMenuItem("🪶 Ma'at (QA)", "Quality governance")
	mGuard := systray.AddMenuItem("🛡 Start Watchdog", "Guard --watch")

	systray.AddSeparator()

	// ── Quick access ────────────────────────────────────────────────
	mBuildLog := systray.AddMenuItem("📋 Build Log", "Open build-log.html")
	mCaseStudies := systray.AddMenuItem("📊 Case Studies", "Open case-studies.html")

	systray.AddSeparator()
	mQuit := systray.AddMenuItem("Quit Sirsi", "Exit menubar app")

	// ── Background stats loop ───────────────────────────────────────
	cfg := DefaultStatsConfig()
	go func() {
		for {
			snap := CollectStats(cfg)
			lines := snap.FormatMenuItems()
			mStats.SetTitle(lines[0]) // RAM line as primary
			mStats.SetTooltip(snap.StatusLine())

			// Update Ra scope items
			for i, item := range raScopes {
				if i < len(snap.RaScopes) {
					s := snap.RaScopes[i]
					item.SetTitle(fmt.Sprintf("  %s %s — %s", s.Icon, s.Name, s.State))
				} else {
					item.SetTitle("  —")
				}
			}

			time.Sleep(cfg.Interval)
		}
	}()

	// ── Event loop ──────────────────────────────────────────────────
	handlers := SirsiHandlers()
	raHandlers := RaHandlers()

	for {
		select {
		case <-mStats.ClickedCh:
			// Refresh stats immediately on click
			snap := CollectStats(cfg)
			lines := snap.FormatMenuItems()
			mStats.SetTitle(lines[0])
			mStats.SetTooltip(snap.StatusLine())
			for i, item := range raScopes {
				if i < len(snap.RaScopes) {
					s := snap.RaScopes[i]
					item.SetTitle(fmt.Sprintf("  %s %s — %s", s.Icon, s.Name, s.State))
				}
			}
		case <-mRaHeader.ClickedCh:
			_ = OpenCommandCenter() // opens Ra Command Center TUI
		case <-mRaDeploy.ClickedCh:
			_ = raHandlers[0].Execute() // ra deploy
		case <-mRaKill.ClickedCh:
			_ = raHandlers[1].Execute() // ra kill
		case <-mRaCollect.ClickedCh:
			_ = raHandlers[2].Execute() // ra collect
		case <-raScopes[0].ClickedCh:
			snap := CollectStats(cfg)
			if len(snap.RaScopes) > 0 {
				_ = OpenScopeLog(snap.RaScopes[0].Name)
			}
		case <-raScopes[1].ClickedCh:
			snap := CollectStats(cfg)
			if len(snap.RaScopes) > 1 {
				_ = OpenScopeLog(snap.RaScopes[1].Name)
			}
		case <-raScopes[2].ClickedCh:
			snap := CollectStats(cfg)
			if len(snap.RaScopes) > 2 {
				_ = OpenScopeLog(snap.RaScopes[2].Name)
			}
		case <-raScopes[3].ClickedCh:
			snap := CollectStats(cfg)
			if len(snap.RaScopes) > 3 {
				_ = OpenScopeLog(snap.RaScopes[3].Name)
			}
		case <-mScan.ClickedCh:
			_ = handlers[0].Execute() // weigh
		case <-mJudge.ClickedCh:
			_ = handlers[1].Execute() // judge
		case <-mKa.ClickedCh:
			_ = handlers[3].Execute() // ka
		case <-mMaat.ClickedCh:
			_ = handlers[5].Execute() // maat
		case <-mGuard.ClickedCh:
			_ = QuickActions()[0].Execute() // guard --watch
		case <-mBuildLog.ClickedCh:
			_ = OpenBuildLog()
		case <-mCaseStudies.ClickedCh:
			_ = OpenCaseStudies()
		case <-mQuit.ClickedCh:
			systray.Quit()
			return
		}
	}
}

func onExit() {}

// AnkhIcon is the menu bar icon data, generated by the Ankh renderer.
var AnkhIcon = getIcon()
