// Package brand is the single source of truth for the Pantheon visual identity:
// emerald + gold. Every surface — CLI (lipgloss), the TUI, the local dashboard
// HTML, the menubar / SwiftUI app, and SirsiNexus — derives its colors from
// these tokens, so one identity renders in every viewport instead of each
// surface hardcoding its own hex (ADR-038).
//
// Heritage: green is Sirsi's color; green + gold are Pantheon's. Emerald leads —
// identity, healthy, and interactive affordances — and gold is the second accent
// for owner-action and the Horus glyph. The prior gold-primary + lapis palette
// (PANTHEON_RULES A10 v1) is superseded by this file.
package brand

import (
	"fmt"
	"strings"
)

// Role is a SEMANTIC color role, never a decorative one. Callers name a role;
// the render layer resolves it to a hex for the active Scheme. This is what lets
// one token mean the same thing on every surface.
type Role int

const (
	Emerald Role = iota // brand identity · healthy · interactive
	Gold                // second accent · owner-action · Horus glyph
	OK                  // pass / safe / healthy (emerald family)
	Warn                // needs attention / reclaimable
	Danger              // destructive / error / protected-path block
	Info                // neutral informational
	Dim                 // chrome / hints / truncation
	Ink                 // primary text
	Ink2                // secondary text
	Bg                  // page ground
	Panel               // raised surface
	Line                // hairline / divider
)

// roleName is the stable token name a role emits as (CSS var, Swift case, JSON
// key). Ordered by the Role iota so emitted output is deterministic.
var roleName = map[Role]string{
	Emerald: "emerald", Gold: "gold", OK: "ok", Warn: "warn", Danger: "danger",
	Info: "info", Dim: "dim", Ink: "ink", Ink2: "ink2", Bg: "bg", Panel: "panel", Line: "line",
}

// allRoles is roleName's keys in iota order — the canonical emission sequence.
var allRoles = []Role{Emerald, Gold, OK, Warn, Danger, Info, Dim, Ink, Ink2, Bg, Panel, Line}

// Name returns the stable token name for a role ("emerald", "gold", …).
func (r Role) Name() string { return roleName[r] }

// Scheme selects the light or dark rendering of the palette.
type Scheme int

const (
	Dark Scheme = iota
	Light
)

// Palette is the resolved hex for every Role in one Scheme.
type Palette map[Role]string

var (
	dark = Palette{
		Emerald: "#2bd29b", Gold: "#cdad5a",
		OK: "#2bd29b", Warn: "#e0913a", Danger: "#f2545b", Info: "#5a9bc9",
		Dim: "#7a8a7f", Ink: "#e6efe9", Ink2: "#a7b6ab",
		Bg: "#0c1310", Panel: "#141c17", Line: "#253229",
	}
	light = Palette{
		Emerald: "#0f7a54", Gold: "#8a6d1f",
		OK: "#0f7a54", Warn: "#9a5f14", Danger: "#c0353b", Info: "#2f5aa8",
		Dim: "#657268", Ink: "#16211b", Ink2: "#465049",
		Bg: "#e9ede8", Panel: "#f6f9f3", Line: "#d3ddce",
	}
)

// For returns the canonical palette for a scheme (Dark is the default; terminals
// are dark-ground, so CLI and TUI resolve against Dark).
func For(s Scheme) Palette {
	if s == Light {
		return light
	}
	return dark
}

// Hex resolves one role. An unknown role returns "" — callers should only pass
// the exported Role constants, so this cannot happen with well-typed input.
func (p Palette) Hex(r Role) string { return p[r] }

// ── Emitters: every non-Go surface derives its tokens from here ──────────────

// CSSVars renders the scheme as CSS custom properties, e.g. `--emerald:#2bd29b;`.
// Consumed by the local dashboard HTML, published Artifacts, and SirsiNexus.
func CSSVars(s Scheme) string {
	p := For(s)
	var b strings.Builder
	for _, r := range allRoles {
		fmt.Fprintf(&b, "--%s: %s;\n", r.Name(), p.Hex(r))
	}
	return b.String()
}

// SwiftColors renders a SwiftUI `Color` extension carrying both schemes, so the
// menubar and the Swift app resolve the SAME hex the CLI does. Emitted rather
// than hand-authored so macapp can never drift from this file.
func SwiftColors() string {
	var b strings.Builder
	b.WriteString("// Generated by `sirsi brand tokens --format swift` — DO NOT EDIT.\n")
	b.WriteString("// Single source: internal/brand/brand.go (ADR-038).\n")
	b.WriteString("import SwiftUI\n\n")
	b.WriteString("extension Color {\n    enum Pantheon {\n")
	for _, r := range allRoles {
		fmt.Fprintf(&b, "        static let %s = Color(light: \"%s\", dark: \"%s\")\n",
			r.Name(), light.Hex(r), dark.Hex(r))
	}
	b.WriteString("    }\n}\n\n")
	b.WriteString("private extension Color {\n")
	b.WriteString("    init(light: String, dark: String) {\n")
	b.WriteString("        self.init(uiColorHex: light, darkHex: dark)\n    }\n}\n")
	return b.String()
}

// JSON renders both schemes as a stable object: {\"dark\":{...},\"light\":{...}}.
// Hand-rolled (no encoding/json) to guarantee deterministic key order for diffs
// and cross-tool consumers ([[feedback_json_arch_code]]).
func JSON() string {
	var b strings.Builder
	b.WriteString("{\n")
	writeScheme(&b, "dark", dark, true)
	writeScheme(&b, "light", light, false)
	b.WriteString("}\n")
	return b.String()
}

func writeScheme(b *strings.Builder, name string, p Palette, more bool) {
	fmt.Fprintf(b, "  %q: {\n", name)
	for i, r := range allRoles {
		comma := ","
		if i == len(allRoles)-1 {
			comma = ""
		}
		fmt.Fprintf(b, "    %q: %q%s\n", r.Name(), p.Hex(r), comma)
	}
	if more {
		b.WriteString("  },\n")
	} else {
		b.WriteString("  }\n")
	}
}

// Roles returns every role in canonical (iota) order — for swatch tables and
// tooling. Do not sort the result; the order is the emission contract.
func Roles() []Role { return allRoles }
