package main

// ctrinstall.go — wire CTR onto a machine so `ctr` and `/ctr` work everywhere.
//
// `sirsi ctr --install` writes two thin adapters over `sirsi ctr`:
//   1. a PATH shim (`ctr`) so any shell / IDE terminal — mac, linux, windows,
//      headless or resident — can type `ctr`;
//   2. the user-global Claude skill (`~/.claude/skills/ctr/SKILL.md`) so `/ctr`
//      is known to every Claude Code session in every repo, present and future.
//
// Both are regenerable and idempotent. `sirsi setup` calls this so a fresh
// install of Pantheon on any machine gets CTR with no extra step.

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// InstallCTR writes the shim + skill and returns a human-readable summary of
// what changed. Exported so `sirsi setup` can call it as part of a full install.
func InstallCTR() (summary []string, err error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("resolve home: %w", err)
	}
	sirsiBin := resolveSirsiBinary()

	shimPath, shimBody := ctrShim(home, sirsiBin)
	if err := writeFileMode(shimPath, shimBody, 0o755); err != nil {
		return nil, fmt.Errorf("write ctr shim: %w", err)
	}
	summary = append(summary, "shim  "+shimPath)

	skillPath := filepath.Join(home, ".claude", "skills", "ctr", "SKILL.md")
	if err := writeFileMode(skillPath, ctrSkillBody(), 0o644); err != nil {
		return nil, fmt.Errorf("write /ctr skill: %w", err)
	}
	summary = append(summary, "skill "+skillPath)

	return summary, nil
}

func runCtrInstall() error {
	summary, err := InstallCTR()
	if err != nil {
		return err
	}
	fmt.Println("𓁢 CTR installed — `ctr` (shell) and `/ctr` (Claude) now available.")
	for _, s := range summary {
		fmt.Println("   ✓ " + s)
	}
	home, _ := os.UserHomeDir()
	binDir := filepath.Join(home, ".local", "bin")
	fmt.Printf("\n   Ensure %s is on your PATH, then run `ctr` from any directory.\n", binDir)
	if runtime.GOOS == "windows" {
		fmt.Printf("   (Windows: add it with  setx PATH \"%s;%s\")\n", "%PATH%", binDir)
	}
	return nil
}

// ctrShim returns the platform-appropriate shim path and body. The shim prefers
// `sirsi` on PATH and falls back to the absolute path of the installing binary,
// so it keeps working even where PATH is stripped (cron, launchd, CI).
func ctrShim(home, sirsiBin string) (path, body string) {
	binDir := filepath.Join(home, ".local", "bin")
	if runtime.GOOS == "windows" {
		body = fmt.Sprintf("@echo off\r\n"+
			"where sirsi >nul 2>nul && (sirsi ctr %%*) || (%q ctr %%*)\r\n", sirsiBin)
		return filepath.Join(binDir, "ctr.cmd"), body
	}
	body = fmt.Sprintf("#!/bin/sh\n"+
		"# CTR — Check The Router. Generated by `sirsi ctr --install`; safe to regenerate.\n"+
		"SIRSI=\"$(command -v sirsi 2>/dev/null || echo %q)\"\n"+
		"exec \"$SIRSI\" ctr \"$@\"\n", sirsiBin)
	return filepath.Join(binDir, "ctr"), body
}

// resolveSirsiBinary returns the best absolute path to embed in the shim as the
// PATH fallback: the running executable, or "sirsi" if that cannot be resolved.
func resolveSirsiBinary() string {
	if exe, err := os.Executable(); err == nil {
		if resolved, rerr := filepath.EvalSymlinks(exe); rerr == nil {
			return resolved
		}
		return exe
	}
	return "sirsi"
}

func writeFileMode(path, body string, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(body), mode)
}

// ctrSkillBody is the canonical `/ctr` skill. It is the SAME text committed to
// the repo at .claude/skills/ctr/SKILL.md, so the user-global copy and the
// repo-shipped copy never drift.
func ctrSkillBody() string {
	return `---
name: ctr
description: Check The Router — surface pending router items and wake stranded agent threads. Run when you (or the owner) says "ctr" / "check the router", on session start, or whenever the router may have unread items.
---

You are running CTR ("Check The Router") for this workstation.

CTR is the universal, on-demand wake primitive: one synchronous pass, no daemon.
It surfaces every open router inbox item and wakes agents that have work waiting
but no live watcher. It is safe to run repeatedly.

Steps:

1. Run ` + "`ctr`" + ` (or ` + "`sirsi ctr`" + ` if the shim is not on PATH). For machine
   consumption use ` + "`sirsi ctr --json`" + `.
2. Read the output:
   - "Woke this pass" — agents a wake was just attempted for.
   - "Stranded" — open items with NO live watcher; that agent's session must run ctr.
   - "Heartbeat-fresh" — a session is checked in, but fresh != consuming; if its
     items still aren't moving, THAT session must run /ctr to pull them.
   - "Needs owner — wake-unavailable" — a closed interactive session that local
     code cannot resurrect; surface these to the owner plainly, do not fake them.
3. If any surfaced items are addressed to YOUR agent id, act on them now: read
   each with ` + "`sirsi router show <id>`" + `, do the work, then ` + "`sirsi router close <id>`" + `
   (or route a response back). Then stop.
4. Report a one-line summary: how many pending, how many woke, how many need the
   owner.

Notes:
- CTR never blind-spawns interactive sessions; "needs-owner" is honest, not a failure.
- The router is found from the current repo, or from ~/.sirsi/pantheon-repo, so
  ` + "`ctr`" + ` works from any directory.
`
}
