package rules

import (
	"context"

	"github.com/SirsiMaster/sirsi-pantheon/internal/cleaner"
	"github.com/SirsiMaster/sirsi-pantheon/internal/jackal"
)

// NewKaGhostRule provides a Clean() implementation for ghost findings.
// Ghost findings are generated inline by runWeigh (not by this rule's Scan),
// but the engine needs a registered rule to dispatch Clean() calls.
func NewKaGhostRule() jackal.ScanRule {
	return &kaGhostRule{}
}

type kaGhostRule struct{}

func (r *kaGhostRule) Name() string              { return "ka_ghost" }
func (r *kaGhostRule) DisplayName() string       { return "Ghost App Residuals" }
func (r *kaGhostRule) Category() jackal.Category { return jackal.CategoryGeneral }
func (r *kaGhostRule) Description() string       { return "Dead app remnants detected by Ka ghost scanner" }
func (r *kaGhostRule) Platforms() []string       { return []string{"darwin", "linux"} }

// Scan is a no-op — ghost findings are generated by Ka in runWeigh, not here.
func (r *kaGhostRule) Scan(ctx context.Context, opts jackal.ScanOptions) ([]jackal.Finding, error) {
	return nil, nil
}

// Clean removes ghost residual files by moving to Trash.
func (r *kaGhostRule) Clean(ctx context.Context, findings []jackal.Finding, opts jackal.CleanOptions) (*jackal.CleanResult, error) {
	result := &jackal.CleanResult{}
	for _, f := range findings {
		freed, err := cleaner.DeleteFile(f.Path, opts.DryRun, opts.UseTrash)
		if err != nil {
			result.Skipped++
			result.Errors = append(result.Errors, err)
			continue
		}
		result.Cleaned++
		result.BytesFreed += freed
	}
	return result, nil
}
