package router

// relayagent.go — the per-host relay LaunchAgent (ADR-062 step 20a.4). One
// resident `sirsi router relay serve` per host holds the router service token;
// lanes talk to it through the spool and carry no token. The plist is the only
// file on the host that contains the token, so it is written privately (0600,
// temp + rename) and tightened on the idempotent path, like the wake plists.

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/SirsiMaster/sirsi-pantheon/internal/routerstore"
	"time"
)

// RelayLaunchAgentLabel is the launchd label of the host relay.
const RelayLaunchAgentLabel = "ai.sirsi.router.relay"

// RelayLaunchAgentPlist renders the relay plist. url/token are the SERVICE
// address and this host's token — never a spool:// URL, which is for lanes.
func RelayLaunchAgentPlist(sirsiBin, spool, url, token string) string {
	home, _ := os.UserHomeDir()
	logPath := filepath.Join(home, ".sirsi", "logs", "router-relay.log")
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>%s</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>%s</string>
    <key>SIRSI_ROUTER_URL</key>
    <string>%s</string>
    <key>SIRSI_ROUTER_TOKEN</key>
    <string>%s</string>
  </dict>
  <key>ProgramArguments</key>
  <array>
    <string>%s</string>
    <string>router</string>
    <string>relay</string>
    <string>serve</string>
    <string>--spool</string>
    <string>%s</string>
  </array>
  <key>KeepAlive</key>
  <true/>
  <key>RunAtLoad</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>%s</string>
  <key>StandardErrorPath</key>
  <string>%s</string>
</dict>
</plist>
`, RelayLaunchAgentLabel, escapeXML(LaunchAgentPATH(sirsiBin)), escapeXML(url), escapeXML(token), escapeXML(sirsiBin), escapeXML(spool), escapeXML(logPath), escapeXML(logPath))
}

// runningExecutable resolves THIS process's binary to an absolute, symlink-free
// path and checks it is a regular file with an execute bit. The relay
// LaunchAgent is scoped to the running binary on purpose: a caller-supplied
// path would let an installer point launchd at anything (SSA 2026-09-10).
func runningExecutable() (string, error) {
	self, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("relay install: resolve running binary: %w", err)
	}
	return checkExecutable(self)
}

// checkExecutable is the identity check behind runningExecutable, separated so
// the refusals can be exercised with fixtures.
func checkExecutable(p string) (string, error) {
	if !filepath.IsAbs(p) {
		return "", fmt.Errorf("relay install: executable %q is not absolute", p)
	}
	canon, err := filepath.EvalSymlinks(p)
	if err != nil {
		return "", fmt.Errorf("relay install: executable %s: %w", p, err)
	}
	st, err := os.Stat(canon)
	if err != nil {
		return "", err
	}
	if !st.Mode().IsRegular() {
		return "", fmt.Errorf("relay install: executable %s is not a regular file", canon)
	}
	if st.Mode().Perm()&0o111 == 0 {
		return "", fmt.Errorf("relay install: %s is not executable", canon)
	}
	return canon, nil
}

// InstallRelayLaunchAgent writes the relay plist privately for the RUNNING
// binary, then bootstraps exactly the bytes it wrote. It returns whether the
// plist content changed and its path. The spool must pass CheckSpoolDir and the
// plist on disk must match the generated bytes at 0600 immediately before
// launchctl sees it; anything else fails closed.
func InstallRelayLaunchAgent(spool, url, token string) (changed bool, path string, err error) {
	url, err = routerstore.CheckServiceURL(url)
	if err != nil {
		return false, "", fmt.Errorf("relay install: %w", err)
	}
	if strings.TrimSpace(token) == "" {
		return false, "", fmt.Errorf("relay install: SIRSI_ROUTER_TOKEN is empty; the relay is the host's token holder")
	}
	sirsiBin, err := runningExecutable()
	if err != nil {
		return false, "", err
	}
	spool, err = routerstore.CheckSpoolDir(spool)
	if err != nil {
		return false, "", fmt.Errorf("relay install: %w", err)
	}
	dir := launchAgentsDir()
	if err = os.MkdirAll(dir, 0o755); err != nil {
		return false, "", err
	}
	if home, herr := os.UserHomeDir(); herr == nil {
		if err = os.MkdirAll(filepath.Join(home, ".sirsi", "logs"), 0o755); err != nil {
			return false, "", err
		}
	}
	path = filepath.Join(dir, RelayLaunchAgentLabel+".plist")
	content := RelayLaunchAgentPlist(sirsiBin, spool, url, token)
	changed, path, err = writePrivatePlist(path, content)
	if err != nil {
		return false, path, err
	}
	if err = verifyPlist(path, content); err != nil {
		return changed, path, err
	}
	return changed, path, loadRelayAgent(path, content)
}

// verifyPlist fails closed unless path is a regular, non-symlink file at 0600
// whose bytes equal content — the identity launchctl is about to consume.
func verifyPlist(path, content string) error {
	st, err := os.Lstat(path)
	if err != nil {
		return fmt.Errorf("relay install: plist: %w", err)
	}
	if st.Mode()&os.ModeSymlink != 0 || !st.Mode().IsRegular() {
		return fmt.Errorf("relay install: %s is not a regular file; refusing to bootstrap", path)
	}
	if st.Mode().Perm() != 0o600 {
		return fmt.Errorf("relay install: %s mode %o, want 0600; refusing to bootstrap", path, st.Mode().Perm())
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !bytes.Equal(b, []byte(content)) {
		return fmt.Errorf("relay install: %s does not match the generated plist (substituted or changed after write); refusing to bootstrap", path)
	}
	return nil
}

// writePrivatePlist writes content to path at 0600 via a same-directory temp
// file and rename; an existing identical file is chmod'ed to 0600 and reported
// unchanged.
func writePrivatePlist(path, content string) (bool, string, error) {
	if existing, rerr := os.ReadFile(path); rerr == nil && string(existing) == content {
		if cerr := os.Chmod(path, 0o600); cerr != nil {
			return false, path, fmt.Errorf("secure plist: %w", cerr)
		}
		return false, path, nil
	}
	tmp, terr := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*")
	if terr != nil {
		return false, path, fmt.Errorf("write plist: %w", terr)
	}
	tmpName := tmp.Name()
	_, err := tmp.WriteString(content)
	if err == nil {
		err = tmp.Chmod(0o600)
	}
	if cerr := tmp.Close(); err == nil {
		err = cerr
	}
	if err == nil {
		err = os.Rename(tmpName, path)
	}
	if err != nil {
		_ = os.Remove(tmpName)
		return false, path, fmt.Errorf("write plist: %w", err)
	}
	return true, path, nil
}

// loadRelayAgent re-verifies the plist identity immediately before launchctl
// consumes it, boots out any previous job (absence is fine) and bootstraps.
// Unexported: only the installer's generated identity reaches launchd.
// loadRelayAgentFn is the seam tests use to keep launchctl out of the run.
var loadRelayAgentFn = func(plistPath string) error {
	target := fmt.Sprintf("gui/%d/%s", os.Getuid(), RelayLaunchAgentLabel)
	loaded := func() bool { return runLaunchctl("print", target) == nil }
	if loaded() {
		_ = runLaunchctl("bootout", target)
		// bootout returns before the job is gone; bootstrapping too early fails
		// with EIO (observed 2026-09-10 on the M5). Wait for it to leave.
		for i := 0; i < 50 && loaded(); i++ {
			time.Sleep(100 * time.Millisecond)
		}
	}
	if err := runLaunchctl("bootstrap", fmt.Sprintf("gui/%d", os.Getuid()), plistPath); err != nil {
		if loaded() { // already resident: restart it on the new plist instead of failing
			if kerr := runLaunchctl("kickstart", "-k", target); kerr == nil {
				return nil
			}
		}
		return fmt.Errorf("launchctl bootstrap %s: %w", RelayLaunchAgentLabel, err)
	}
	return nil
}

func loadRelayAgent(plistPath, content string) error {
	if err := verifyPlist(plistPath, content); err != nil {
		return err
	}
	return loadRelayAgentFn(plistPath)
}
