// Package main — pantheon-menubar
//
// 𓂀 Pantheon Menu Bar Application (ADR-010)
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"fyne.io/systray"
	"github.com/SirsiMaster/sirsi-pantheon/internal/platform"
)

var version = "v0.4.0-alpha"

func main() {
	// Check if this is the only instance running
	unlock, err := platform.TryLock("menubar")
	if err != nil {
		fmt.Printf("𓂀 Pantheon Menubar is already running. Exiting.\n")
		os.Exit(0)
	}
	defer unlock()

	// Check if we should run in headless mode
	if os.Getenv("PANTHEON_HEADLESS") == "1" {
		runHeadless()
		return
	}

	systray.Run(onReady, onExit)
}

func runHeadless() {
	fmt.Printf("𓂀 Pantheon Menubar %s (Headless Mode)\n", version)
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, syscall.SIGTERM)
	<-sigCh
}

func onReady() {
	systray.SetTemplateIcon(AnkhIcon, AnkhIcon)
	systray.SetTitle("Pantheon")
	systray.SetTooltip("Pantheon Ecosystem Monitor")

	mStats := systray.AddMenuItem("Stats: Scanning...", "System status")
	systray.AddSeparator()
	mQuit := systray.AddMenuItem("Quit", "Quit Pantheon")

	go func() {
		for {
			select {
			case <-mQuit.ClickedCh:
				systray.Quit()
				return
			case <-time.After(5 * time.Second):
				mStats.SetTitle("RAM: Optimized")
			}
		}
	}()
}

func onExit() {
	// Cleanup happens via defer unlock() in main
}

// AnkhIcon is the menu bar icon data, generated by the Ankh renderer.
var AnkhIcon = getIcon()
